# Generated by Django 2.2.10 on 2020-06-01 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20180312_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnionGroup',
            fields=[
                ('abstractgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groups.AbstractGroup')),
                ('groups', models.ManyToManyField(help_text='Объединение каких групп построить', related_name='_uniongroup_groups_+', to='groups.AbstractGroup')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('groups.abstractgroup',),
        ),
        migrations.CreateModel(
            name='IntersectionGroup',
            fields=[
                ('abstractgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groups.AbstractGroup')),
                ('groups', models.ManyToManyField(help_text='Пересечение каких групп построить', related_name='_intersectiongroup_groups_+', to='groups.AbstractGroup')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('groups.abstractgroup',),
        ),
        migrations.CreateModel(
            name='DifferenceGroup',
            fields=[
                ('abstractgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groups.AbstractGroup')),
                ('from_group', models.ForeignKey(help_text='Участников какой группы взять', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='groups.AbstractGroup')),
                ('not_from_group', models.ForeignKey(help_text='Участников какой группы вычесть из участников первой группы', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='groups.AbstractGroup')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('groups.abstractgroup',),
        ),
    ]
