# Generated by Django 4.0.10 on 2024-02-26 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('groups', '0006_auto_20211229_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractgroup',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='groupaccess',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='intersectiongroup',
            name='groups',
            field=models.ManyToManyField(help_text='Пересечение каких групп построить', related_name='+', to='groups.abstractgroup'),
        ),
        migrations.AlterField(
            model_name='uniongroup',
            name='groups',
            field=models.ManyToManyField(help_text='Объединение каких групп построить', related_name='+', to='groups.abstractgroup'),
        ),
    ]
