# Generated by Django 2.2.10 on 2020-06-01 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20180312_2139'),
        ('questionnaire', '0017_auto_20181111_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersSelectedQuestionVariant',
            fields=[
                ('abstractgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groups.AbstractGroup')),
                ('variant', models.ForeignKey(help_text='В группу автоматически попадут все пользователи, выбравшие этот вариант ответа', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questionnaire.ChoiceQuestionnaireQuestionVariant')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('groups.abstractgroup',),
        ),
    ]
