# Generated by Django 2.2.10 on 2020-06-01 18:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_auto_20180407_1742'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dates', '0008_auto_20180510_2140'),
        ('groups', '0004_auto_20180312_2139'),
        ('questionnaire', '0018_usersselectedquestionvariant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersSelectedQuestionVariant',
            new_name='UsersSelectedQuestionVariantGroup',
        ),
    ]
