version: 2
updates:
- package-ecosystem: pip
  directory: "/src"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: reportlab
    versions:
    - 3.5.60
    - 3.5.62
    - 3.5.63
    - 3.5.64
    - 3.5.65
    - 3.5.66
  - dependency-name: pyjwt
    versions:
    - 2.0.1
  - dependency-name: django-ses
    versions:
    - 1.0.3
  - dependency-name: django
    versions:
    - 2.2.13
