language: python
cache: pip

python:
  - "3.5"
  - "3.6"

env:
  - CORE_APPS: dates frontend generator groups home questionnaire schools sistema users

install:
  - pip install -r src/requirements.txt

script:
  - python src/web/manage.py migrate
  - python src/web/manage.py test ${CORE_APPS} modules
