language: python
cache: pip

python:
  - "3.5"
  - "3.6"

env:
  global:
    - CORE_APPS="dates frontend generator groups home questionnaire schools sistema users"
    - REQUIREMENTS=src/requirements.txt

matrix:
  include:
    - env: DB=sqlite

    - env: DB=mysql REQUIREMENTS=src/requirements.mysql.txt
      services: mysql
      before_script: mysql -e "CREATE DATABASE travis_db CHARACTER SET utf8;" -u root

    - env: DB=postgres REQUIREMENTS=src/requirements.postgres.txt
      services: postgresql
      before_script: psql -c "CREATE DATABASE travis_db;" -U postgres

install:
  - cp src/web/sistema/travis_settings.py src/web/sistema/local_settings.py
  - pip install -r ${REQUIREMENTS}

script:
  - python src/web/manage.py makemigrations --check
  - python src/web/manage.py migrate
  - python src/web/manage.py test ${CORE_APPS} modules
