# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 19:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160730_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('sex', models.PositiveIntegerField(choices=[(1, 'женский'), (2, 'мужской')], validators=[djchoices.choices.ChoicesValidator({1: 'женский', 2: 'мужской'})], verbose_name='Пол')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('zero_class_year', models.PositiveIntegerField(help_text='используется для вычисления текущего класса', null=True, verbose_name='Год поступления в "нулевой" класс')),
                ('region', models.CharField(blank=True, help_text='или страна, если не Россия', max_length=100, verbose_name='Субъект РФ')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Населённый пункт')),
                ('school_name', models.CharField(blank=True, max_length=100, verbose_name='Школа')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Национальность')),
                ('document_type', models.PositiveIntegerField(choices=[(0, ''), (1, 'российский паспорт'), (2, 'свидетельство о рождении'), (3, 'заграничный паспорт')], validators=[djchoices.choices.ChoicesValidator({0: '', 1: 'российский паспорт', 2: 'свидетельство о рождении', 3: 'заграничный паспорт'})], verbose_name='Тип документа')),
                ('document_number', models.CharField(max_length=20, verbose_name='Номер документа')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
