# Generated by Django 4.0.10 on 2024-02-26 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20211229_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='users',
            field=models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
