# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 16:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_school_full_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entrance', '0003_auto_20160330_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceUserUpgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entranceuserupgrade', to='school.School')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
