# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0004_entranceuserupgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='entranceuserupgrade',
            name='advanced_by',
            field=models.IntegerField(default=1),
        ),
    ]
