# Generated by Django 2.2.10 on 2021-05-09 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_auto_20180407_1742'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entrance', '0087_auto_20210509_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entranceexam',
            name='can_participant_select_entrance_level',
            field=models.BooleanField(default=False, help_text='Может ли школьник выбрать себе уровень вступительной работы.<br>Если отмечено, то школьнику будет предоставлен выбор, начиная с минимального уровня, на который он может претендовать.<br>Если не отмечено, то уровень выдаётся автоматически на основе тематической анкеты и других параметров. При решении определённых задач школьник может поднять себе уровень.'),
        ),
        migrations.CreateModel(
            name='SelectedEntranceLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='entrance.EntranceLevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
