# Generated by Django 2.2.10 on 2021-05-10 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0088_auto_20210509_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrancelevel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_levels', to='schools.School'),
        ),
        migrations.AlterField(
            model_name='selectedentrancelevel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
