# Generated by Django 2.2.10 on 2021-05-19 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0089_auto_20210510_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedenrollmenttype',
            name='accepted_entrance_level',
            field=models.ForeignKey(blank=True, default=None, help_text='Зачтённый уровень вступительной. Задачи этого уровня школьнику решать не надо, они зачтены автоматически. Должно коррелировать с выданным уровнем вступительной (см. ниже)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entrance.EntranceLevel', verbose_name='зачтенный уровень вступительной'),
        ),
        migrations.AlterField(
            model_name='selectedenrollmenttype',
            name='entrance_level',
            field=models.ForeignKey(blank=True, default=None, help_text='[Устарело, используйте «зачтённый уровень вступительной»] Выставленный уровень вступительной. Должен содержать задачи, необходимые для поступления в следующую параллель после той, в которую школьник зачислен автоматически. Если не указать, то автоматически посчитается как уровень, следующий за «зачтённый уровень вступительной»', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entrance.EntranceLevel', verbose_name='уровень вступительной'),
        ),
    ]
