# Generated by Django 3.2.13 on 2022-05-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0091_auto_20211229_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedenrollmenttype',
            name='allow_pass_entrance_exam',
            field=models.BooleanField(default=True, help_text='Если False, то школьнику будет недоступно выполнение вступительной работы ни на каком уровне. Технически эквивалентно тому, чтобы выставить «зачтённый уровень вступительной» в максимально возможный уровень. Отличается в формулировках, видимых пользователю.', verbose_name='разрешить ли сдавать вступительную'),
        ),
    ]
