# Generated by Django 3.2.13 on 2022-05-24 17:34

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20211229_1503'),
        ('entrance', '0092_selectedenrollmenttype_allow_pass_entrance_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceStatusesGroup',
            fields=[
                ('abstractgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groups.abstractgroup')),
                ('statuses', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Не участвовал в конкурсе'), (2, 'Автоматический отказ'), (3, 'Не прошёл по конкурсу'), (4, 'Поступил'), (5, 'Подал заявку'), (6, 'В резервном списке')], max_length=11)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('groups.abstractgroup',),
        ),
    ]
