# Generated by Django 3.2.13 on 2022-05-24 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20211229_1503'),
        ('entrance', '0093_entrancestatusesgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='entranceexamtask',
            name='visible_only_for_group',
            field=models.ForeignKey(blank=True, help_text='Здесь можно указать группу школьников. Тогда эта задача будет видна только этим школьникам.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='groups.abstractgroup'),
        ),
    ]
