# Generated by Django 3.2.13 on 2022-05-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0094_entranceexamtask_visible_only_for_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancelevellimiter',
            name='is_recommendation_only_limiter',
            field=models.BooleanField(default=False, help_text='Если True, то лимитер на самом деле не участвует в ограничении доступных уровней, а влияет только на показ «рекомендуемого» уровня'),
        ),
        migrations.AlterField(
            model_name='entranceexamtask',
            name='text',
            field=models.TextField(blank=True, help_text='Формулировка задания'),
        ),
    ]
