# Generated by Django 3.2.18 on 2023-06-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0095_auto_20220527_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmenttype',
            name='is_disabled',
            field=models.BooleanField(default=False, help_text='Выключена ли возможность выбрать этот тип поступления'),
        ),
    ]
