exclude = [
    ".git",
    ".venv",
    ".vscode",
    "site-packages",
    "venv",

    "migrations"
]


[lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
