# Generated by Django 2.2.10 on 2021-07-20 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_differencegroup_intersectiongroup_uniongroup'),
        ('enrolled_scans', '0009_auto_20180526_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedEnrolledScanGroup',
            fields=[
                ('abstractgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groups.AbstractGroup')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enrolled_scans.EnrolledScanRequirement')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('groups.abstractgroup',),
        ),
    ]
