# Generated by Django 4.0.10 on 2024-02-26 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('enrolled_scans', '0011_auto_20211229_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledscanrequirementcondition',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
