# Generated by Django 2.2.10 on 2021-07-01 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_differencegroup_intersectiongroup_uniongroup'),
        ('finance', '0016_paymentamount_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDocumentGenerationCondition',
            fields=[
                ('abstractdocumentgenerationcondition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.AbstractDocumentGenerationCondition')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='groups.AbstractGroup')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('finance.abstractdocumentgenerationcondition',),
        ),
    ]
