# Generated by Django 4.0.10 on 2024-02-26 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0020_auto_20211229_1503'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('finance', '0018_auto_20211229_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractdocumentgenerationcondition',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='required_questions',
            field=models.ManyToManyField(blank=True, related_name='+', to='questionnaire.abstractquestionnairequestion'),
        ),
    ]
