name: CI & Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    name: Python ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./src/requirements.dev.txt
        cp src/web/sistema/ci_settings.py src/web/sistema/local_settings.py
    - name: Migrate
      run: |
        python src/web/manage.py makemigrations --check
        python src/web/manage.py migrate
    - name: Run Tests
      run: |
        pytest src/web
    - name: Run Linter
      run: |
        ruff check src/web
